config/routes.rb
Rails.application.routes.draw do
  root 'tweets#new'
  resources :tweets, only: [:new, :create] do
    collection do
      get 'post'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :twitter_client, except: :new

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(create_params)
    redirect_to :root
  end

  def twitter_client
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key = "41HEMf5GXcG4w7zf3yRKqHi6S"
      config.consumer_secret = "BKj23RAe4ffFgZs65oKhcpgFqOdY8NO6HfBwTUcG7773BD4gCe"
      config.access_token = "864034106157309952-FSbM0NYlncWi66075FZZhKLPwpuGPeD"
      config.access_token_secret = "WNyCr6j8vN6WnlY1bcCW6LDFBDeg2004xRsR20dLkeurr"
    end
  end

  def post
    tweet = Tweet.order('RANDOM()').first
    status = tweet.text
    media = open(tweet.image)
    @client.update_with_media(status, media)
    redirect_to :root
  end

  private
  def create_params
    params.require(:tweet).permit(:text, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterBot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/new.html.erb
<%= form_for @tweet do |f| %>
  <%= f.text_area :text, cols: 40, rows: 5 ,maxlength: 140 %>
  <%= f.text_field :image %>
  <%= f.submit '保存' %>
<% end %>
<hr>
<button type="submit" style = "width: 70px; height: 25px;"><%= link_to 'ツイート', post_tweets_path %></button>